### ISSUE TITLE
Network setup issues 

### ISSUE THREAD

**Issue by zms5063** [waveform80/compoundpi#30]
Hello, Dave Compoundpi seems perfect for my application based on reading the documentation, however im having trouble setting up my network settings, and am very weak in that area of computer science. I'm a university student, and would definetely be will to issue citations if you have any relevant published work on compoundpi, should my project get off the ground. My email is zms5063@psu.edu if you would prefer to contact me that way.

**Comment by waveform80** [comment]
Just for my reference, here's a link to the corresponding [forum post](https://www.raspberrypi.org/forums/viewtopic.php?p=790179&sid=b57e451803c9d4a29e590c4b84e2c2ef#p790179). In that you state that you haven't seen the red camera light appear on the Pi servers? If so, that's the reason you can't get the client to find any servers: because they're not running. So that's the first thing to sort out.

Connect a monitor and keyboard to one of your Pi servers and from the command line check on whether the cpid daemon is running:

```
$ sudo service cpid status
```

That should return something like "cpid is running" is everything is fine but my guess is it won't. Whatever it does return will likely be useful so if you could paste that here we can go from there.

**Comment by zms5063** [comment]
Yes, I ended up getting it nominally working. It might be helpful to include a list of dependencies in the documentation. I was missing python setuptools, and didn't notice the traceback when I was installing.

**Comment by waveform80** [comment]
I'll add that dependency into the installation instructions for 0.4. Any particular reason you didn't use the Raspbian package? (I know it's rather out of date but it's definitely the simplest way to install and it's the only way that includes an initscript to automatically launch the cpid daemon on boot). I'm working on 0.4 at the moment, and am vaguely hopeful I should have something released in a few days.

**Comment by zms5063** [comment]
I just followed the Server installation instructions in the documentation, perhaps that wasn't correct, this is really the first time I was installing a python library on R-pi, and I'm not experienced in Linux to know when I'm making a goofy mistake.

**Comment by waveform80** [comment]
No worries - I'm adding a note to the installation instructions to install the `pip` command first (that'll pull in setuptools automatically). I've also updated the quick-start stuff for 0.4 and moved it to the front of the docs as it's probably more useful for first-timers while the installation docs are a sort of catch-all for more general platforms.
