### ISSUE TITLE
downloading

### ISSUE THREAD

**Issue by jeremy-rutman** [waveform80/compoundpi#32]
There's an example for downloading with the line

```
with io.open('/home/pi/skygrow/test_images/%s.jpg' % addr,'w') as output:
```

this actually breaks a pipe in our setup (5 servers, raspi2 client) 
This however works:
```
with io.open('/home/pi/skygrow/test_images/%s.jpg' % addr,'wb') as output:
```

**Comment by waveform80** [comment]
Ah, found it - if it's the one you're referring to it's actually missing the file mode entirely (which is why it fails rather than working but producing a corrupt file as the default file mode is `'r'`). For my own reference: it's the first example in `batch.rst` - I'll have this fixed for the next release
